csr.common.name=SERVER-KARAGE-312998361200003
csr.serial.number=1-SERVER|2-SERVER|3-ed22f1d8-e6a2-1118-9b58-d9a8f11e445f
csr.organization.identifier=312998361200003
csr.organization.unit.name=KARAGE HQ
csr.organization.name=شركة كراج لتقنية نظم المعلومات
csr.country.name=SA
csr.invoice.type=1100
csr.location.address=RQRA2935
csr.industry.business.category=انظمة مبيعات


